name: Python Code Quality

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]
    paths:
      - '**.py'

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          find . -name "requirements.txt" -not -path "*/.venv/*" -exec pip install -r {} \;
          pip install pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py') --fail-under=8.0